name: 'dv_metrics'
version: '0.1.0'

profile: 'dv_metrics'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

on-run-start:
  - "{{ dv_metrics.create_dv_metrics_schema() }}"
  - "{{ dv_metrics.create_invocation_log_table() }}"
  - "{{ dv_metrics.create_column_log_table() }}"

on-run-end:
  - "{{ dv_metrics.drop_invocation_log_table() }}"
  - "{{ dv_metrics.drop_column_log_table() }}"

models:
  dv_metrics:
      hubs:
          materialized: incremental
      links:
          materialized: incremental
      satellites:
          materialized: incremental
      pit:
          materialized: view
      dmsa:
          materialized: view
