name: 'dv_metrics'
version: '0.1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  dv_metrics:
      hubs:
          materialized: incremental
      links:
          materialized: incremental
      satellites:
          materialized: incremental
      pit:
          materialized: view
      dmsa:
          materialized: view
